<template>
  <div>
    <v-row>
      <!--다운로드-->
      <v-col>
        <p>파일 다운로드</p>
        <p>내용 수정은 코드의 data에서 text 값을 변경하세요!</p>
        <v-divider></v-divider><br/>
        <div id="text-val" rows="4" v-html="test"></div>
        <br/>
        <input type="button" id="dwn-btn" value="Download file button"/>
      </v-col>
      <!--업로드-->
      <v-col>
        <p>파일 업로드 -> 수정중</p>
        <v-file-input
        accept=".html"
        label="File input"
        v-model="files"
        ></v-file-input>
        <v-btn right @click="importTxt">Read File</v-btn>
        <p>File Name : {{ files.name }}</p>
        <p>text: {{ data }}</p>
      </v-col>
    </v-row>
  </div>
</template>
<script>
//import $ from 'jquery';
export default {
    mounted(){
      function download(filename, text) {
        var element = document.createElement('a');
        element.setAttribute('href', 'data:text/html;charset=utf-8,' + encodeURIComponent(text));
        element.setAttribute('download', filename);

        element.style.display = 'none';
        document.body.appendChild(element);

        element.click();

        document.body.removeChild(element);
      }
// Start file download.
      document.getElementById("dwn-btn").addEventListener("click", function(){
    // Generate download of hello.txt file with some content
        var text = document.getElementById("text-val").innerHTML;
        var filename = "hello.html";
    
        download(filename, text);
      }, false);
    },
    data(){
      return{
        test:`<p>html 파일 다운로드 테스트</p>`,
        files: [],
        data:'',
      }
    },
    methods: {
      importTxt() {
      
      if (!this.files) {this.data = "No File Chosen"}
      var reader = new FileReader();
      
      // Use the javascript reader object to load the contents
      // of the file in the v-model prop
      reader.readAsText(this.files);
      reader.onload = () => {
        this.data = reader.result;
      }
    }
    },
}
</script>
<style>
#dwn-btn {
  background-color: rgb(214, 190, 175);
}
</style>
<!-- diff2html 예시 코드
<template>
<div>
  <span>기능설명, 추가기능: </span><a>https://github.com/rtfpessoa/diff2html#diff2htmlui-usage</a>
  <div v-html="prettyHtml" />
</div>
</template>

<script>
import * as Diff2Html from 'diff2html';
import 'diff2html/bundles/css/diff2html.min.css';

export default {
  data() {
    return {
      diffs:
        '--- a/server/vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go\n+++ b/server/vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go\n@@ -1035,6 +1035,17 @@ func Prctl(option int, arg2 uintptr, arg3 uintptr, arg4 uintptr, arg5 uintptr) (\n \n // THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT\n \n+func Pselect(nfd int, r *FdSet, w *FdSet, e *FdSet, timeout *Timespec, sigmask *Sigset_t) (n int, err error) {\n+\tr0, _, e1 := Syscall6(SYS_PSELECT6, uintptr(nfd), uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(w)), uintptr(unsafe.Pointer(e)), uintptr(unsafe.Pointer(timeout)), uintptr(unsafe.Pointer(sigmask)))\n+\tn = int(r0)\n+\tif e1 != 0 {\n+\t\terr = errnoErr(e1)\n+\t}\n+\treturn\n+}\n+\n+// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT\n+\n func read(fd int, p []byte) (n int, err error) {\n \tvar _p0 unsafe.Pointer\n \tif len(p) > 0 {\n',
    };
  },
  computed: {
    prettyHtml() {
      return Diff2Html.html(this.diffs, {
        drawFileList: true,
        matching: 'lines',
        outputFormat: 'side-by-side',
      });
    },
  },
};
</script>
-->