
<template>
  <div class="editor">
    <editor-menu-bar :editor="editor" v-slot="{ commands, isActive }">
      <div class="menubar">
        <button
          class="menubar__button"
          :class="{ 'is-active': isActive.bold() }"
          @click="commands.bold"
        >
          Bold
        </button>
        <button
          class="menubar__button"
          :class="{
            'is-active': isActive.customstyle({ level: 'body-black' }),
          }"
          @click="commands.customstyle({ level: 'body-black' })"
        >
          Body Green
        </button>
        <button
          class="menubar__button"
          :class="{ 'is-active': isActive.customstyle({ level: 'body-blue' }) }"
          @click="commands.customstyle({ level: 'body-blue' })"
        >
          Body Blue
        </button>
        <button
          class="menubar__button"
          :class="{ 'is-active': isActive.customstyle({ level: 'body-red' }) }"
          @click="commands.customstyle({ level: 'body-red' })"
        >
          Body Red
        </button>
      </div>
    </editor-menu-bar>

    <editor-content
      class="editor__content"
      style="background: rgba(100, 100, 0, 0.2)"
      :editor="editor"
    />
    <pre>{{localHTML}}</pre>
  </div>
</template>

<script>
import { Editor, EditorContent, EditorMenuBar } from "tiptap";
import { Bold } from "tiptap-extensions";
import CustomStyle from "../components/CustomStyle";

export default {
  components: {
    EditorContent,
    EditorMenuBar,
  },
  data() {
    return {
      localJSON: "",
      localHTML: "",
      editor: new Editor({
        extensions: [new Bold(), new CustomStyle()],
        onUpdate: ({ getHTML, getJSON }) => {
          this.localHTML = getHTML();
          this.localJSON = getJSON();
        },
        content: `
          <h2>
            Hi there,
          </h2>
          <p>
            this is a very <em>basic</em> example of tiptap.
          </p>`,
      }),
    };
  },
  beforeDestroy() {
    this.editor.destroy();
  },
};
</script>

<style>
.menubar__button {
  font-weight: 700;
  display: -webkit-inline-box;
  display: -ms-inline-flexbox;
  display: inline-flex;
  background: rgba(0, 0, 0, 0);
  border: 0;
  color: #000;
  padding: 0.2rem 0.5rem;
  margin-right: 0.2rem;
  border-radius: 3px;
  cursor: pointer;
}
.menubar__button:hover {
  background-color: rgba(0, 0, 0, 0.05);
}
.menubar__button.is-active {
  background-color: rgba(0, 0, 0, 0.1);
}
pre {
  white-space: pre-wrap; /* Since CSS 2.1 */
  white-space: -moz-pre-wrap; /* Mozilla, since 1999 */
  white-space: -pre-wrap; /* Opera 4-6 */
  white-space: -o-pre-wrap; /* Opera 7 */
  word-wrap: break-word; /* Internet Explorer 5.5+ */
}
</style>


<!-- diff2html 예시 코드
<template>
<div>
  <span>기능설명, 추가기능: </span><a>https://github.com/rtfpessoa/diff2html#diff2htmlui-usage</a>
  <div v-html="prettyHtml" />
</div>
</template>

<script>
import * as Diff2Html from 'diff2html';
import 'diff2html/bundles/css/diff2html.min.css';

export default {
  data() {
    return {
      diffs:
        '--- a/server/vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go\n+++ b/server/vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go\n@@ -1035,6 +1035,17 @@ func Prctl(option int, arg2 uintptr, arg3 uintptr, arg4 uintptr, arg5 uintptr) (\n \n // THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT\n \n+func Pselect(nfd int, r *FdSet, w *FdSet, e *FdSet, timeout *Timespec, sigmask *Sigset_t) (n int, err error) {\n+\tr0, _, e1 := Syscall6(SYS_PSELECT6, uintptr(nfd), uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(w)), uintptr(unsafe.Pointer(e)), uintptr(unsafe.Pointer(timeout)), uintptr(unsafe.Pointer(sigmask)))\n+\tn = int(r0)\n+\tif e1 != 0 {\n+\t\terr = errnoErr(e1)\n+\t}\n+\treturn\n+}\n+\n+// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT\n+\n func read(fd int, p []byte) (n int, err error) {\n \tvar _p0 unsafe.Pointer\n \tif len(p) > 0 {\n',
    };
  },
  computed: {
    prettyHtml() {
      return Diff2Html.html(this.diffs, {
        drawFileList: true,
        matching: 'lines',
        outputFormat: 'side-by-side',
      });
    },
  },
};
</script>
-->